# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYtUc3_SwprL2SZI78t7uQbANCBRCx3n
"""

# Prerequisites 
# To use this file as module in Colab, you need to import it using "Upload to session storage"
# button from "Files" section. Also, you need to add the dataset into "sample_data" dir.

# Comment these because of getting "syntax error" when ran as imported file
#!pip install pyspark
#!wget -q https://downloads.apache.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz

from pyspark.sql import SparkSession
from pyspark.sql.functions import count

spark1 = SparkSession.builder.appName('Stroke').getOrCreate()
data_frame = spark1.read.csv('/content/sample_data/healthcare-dataset-stroke-data.csv',inferSchema=True,header=True)
data_frame.createOrReplaceTempView("DATA")

def get_data_frame():
  return data_frame

# Show summary information from dataset
def data_summary_show(data_frame):
  data_frame.printSchema()
  data_frame.show()
  data_frame.columns
  data_frame.summary().show()

# Return the cleaned up dataset
def data_cleaning(data_frame):
  print("***Cleaning the dataset***:")
  print("***Drop missing values***")
  data_frame.na.drop()
  data_frame.select('gender').distinct().rdd.map(lambda r: r[0]).collect()
  spark1.sql("SELECT * FROM DATA WHERE GENDER = 'Other'").show()
  print("***Remove gender == 'Other'***:")
  data_frame= data_frame.filter(data_frame.gender != 'Other')
  print("***Remove smoking_status == 'Unknown'***")
  data_frame.select('smoking_status').distinct().rdd.map(lambda r: r[0]).collect()
  data_frame = data_frame.filter(data_frame.smoking_status != 'Unknown')
  print("***Remove bmi == 'N/A'***")
  data_frame = data_frame.filter(data_frame.bmi != 'N/A')
  print("***Drop column 'id'***")
  data_frame= data_frame.drop(data_frame['id'])
  print("***Finished cleaning the dataset***:")

  return data_frame