# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYtUc3_SwprL2SZI78t7uQbANCBRCx3n
"""

# Prerequisites 
# To use this file as module in Colab, you need to import it using "Upload to session storage"
# button from "Files" section. Also, you need to add the dataset into "sample_data" dir.

# Comment these because of getting "syntax error" when ran as imported file
#!pip install pyspark
#!wget -q https://downloads.apache.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz

from pyspark.sql import SparkSession
from pyspark.sql.functions import count

def get_data_frame(spark_session):
  data_frame = spark_session.read.csv('/content/sample_data/healthcare-dataset-stroke-data.csv',inferSchema=True,header=True)
  return data_frame

# Show summary information from dataset
def data_summary_show(data_frame):
  data_frame.printSchema()
  data_frame.show()
  data_frame.columns
  data_frame.count()
  data_frame.summary().show()

# Return the cleaned up dataset
def data_cleaning(data_frame, spark_session):
  print("***Cleaning the dataset***:")
  data_frame.na.drop().count()
  data_frame.select('gender').distinct().rdd.map(lambda r: r[0]).collect()
  spark_session.sql("SELECT * FROM DATA WHERE GENDER = 'Other'").show()
  data_frame= data_frame.filter(data_frame.gender != 'Other')
  data_frame.count()
  data_frame.select('smoking_status').distinct().rdd.map(lambda r: r[0]).collect()
  data_frame = data_frame.filter(data_frame.smoking_status != 'Unknown')
  data_frame.count()
  data_frame.groupBy('gender').count().show()
  data_frame= data_frame.drop(data_frame['id'])
  data_frame.columns
  print("***Finished cleaning the dataset***:")

  return data_frame