# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYtUc3_SwprL2SZI78t7uQbANCBRCx3n
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import count
!wget -q https://downloads.apache.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz

spark1 = SparkSession.builder.appName('Stroke').getOrCreate()

data_frame = spark1.read.csv('/content/sample_data/healthcare-dataset-stroke-data.csv',inferSchema=True,header=True)

data_frame.printSchema()

data_frame.show()

data_frame.columns

data_frame.count()

data_frame.summary().show()