# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYtUc3_SwprL2SZI78t7uQbANCBRCx3n
"""

pip install pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import count
!wget -q https://downloads.apache.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz

spark1 = SparkSession.builder.appName('Stroke').getOrCreate()

data_frame = spark1.read.csv('/content/sample_data/healthcare-dataset-stroke-data.csv',inferSchema=True,header=True)

data_frame.printSchema()

data_frame.show()

data_frame.columns

data_frame.count()

data_frame.summary().show()

#data cleaning
data_frame.na.drop().count()
data_frame.select('gender').distinct().rdd.map(lambda r: r[0]).collect()
spark1.sql("SELECT * FROM DATA WHERE GENDER = 'Other'").show()
data_frame= data_frame.filter(data_frame.gender != 'Other')
data_frame.count()
data_frame.select('smoking_status').distinct().rdd.map(lambda r: r[0]).collect()
data_frame = data_frame.filter(data_frame.smoking_status != 'Unknown')
data_frame.count()
data_frame.groupBy('gender').count().show()
data_frame= data_frame.drop(data_frame['id'])
data_frame.columns
